"""add unit field to Exercise

Revision ID: 0a9b1ba339b3
Revises: 0ee169ed98cd
Create Date: 2026-02-16 07:06:05.236334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9b1ba339b3'
down_revision = '0ee169ed98cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercises', schema=None) as batch_op:
        batch_op.drop_column('unit')

    # ### end Alembic commands ###
