"""remove schedule_days_per_week from Program

Revision ID: 0ee169ed98cd
Revises: 18aff2d15240
Create Date: 2026-02-16 06:49:46.578007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ee169ed98cd'
down_revision = '18aff2d15240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.drop_column('schedule_days_per_week')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_days_per_week', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
